image: Ubuntu

environment:
  SITE_REPO_TOKEN: 
    secure: 8SAVgh13zakRbC2AsxansQ4Cb5sLpFQC1EgdgjNFK0BiVtr1sPwgM//jaHxvum2F

install:
- sudo apt install git wget -y

test_script:
- ps: git clone https://dozzler555:$($env:SITE_REPO_TOKEN)@github.com/dozzler555/ttk source
- sh: cd source
- sh: mkdir torapp
- sh: sudo apt update -y
- sh: sudo apt list --installed
- chmod -R 777 torapp
- export DEBIAN_FRONTEND=noninteractive
- sh: sudo apt -qq install -y curl git wget
- sh: wget https://github.com/rokibhasansagar/slimhub_actions/raw/main/cleanup.sh
- sh: chmod a+x cleanup.sh
- sh: cleanup.sh
- sh: sudo apt install python3-pip -y
- sh: sudo apt install aria2 -y 
- sh: sudo apt install -y ffmpeg mediainfo unzip p7zip-full p7zip-rar
- sh: curl https://rclone.org/install.sh

- sh: sudo apt-get install -y software-properties-common
- sh: sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable
- sh: sudo apt install -y qbittorrent-nox
- sh: pip3 install --no-cache-dir -r requirements.txt
- sh: chmod 777 alive.sh
- sh: chmod 777 start.sh
- sh: sudo bash start.sh
